version: "3.7"
services:
  metricq-manager:
    build:
      context: https://github.com/metricq/metricq-manager.git
    image: metricq-manager
    environment:
      wait_for_couchdb_url: "couchdb-server:5984"
      couchdb_url: "http://couchdb-server:5984"
      couchdb_user: "admin"
      couchdb_pw: "admin"
      WAITFORIT_TIMEOUT: 0
      wait_for_rabbitmq_url: "rabbitmq-server:5672"
      rpc_url: "amqp://admin:admin@rabbitmq-server/"
      data_url: "vhost:/"
    depends_on:
      - rabbitmq-server-node0
      - couchdb-server
      - couchdb-setup
    networks:
      - metricq-network

  db-hta-dummy:
    build:
      context: https://github.com/metricq/metricq-db-hta.git
    image: metricq-db-hta
    depends_on:
      - rabbitmq-server-node0
      - metricq-manager
      - couchdb-setup
    environment:
      token: "db-hta-dummy"
      metricq_url: "amqp://admin:admin@rabbitmq-server"
      wait_for_rabbitmq_url: "rabbitmq-server:5672"
      WAITFORIT_TIMEOUT: 0
    restart: unless-stopped
    networks:
      - metricq-network

  metricq-wizard-frontend:
    build:
      context: https://github.com/metricq/metricq-wizard-frontend.git
      args:
        - api_url=http://localhost:8000/api
    image: metricq-wizard-frontend
    depends_on:
      - metricq-wizard-backend
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - metricq-network

  metricq-wizard-backend:
    build:
      context: https://github.com/metricq/metricq-wizard-backend.git
      args:
        - SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0-dev
    image: metricq-wizard-backend
    environment:
      wait_for_couchdb_url: "couchdb-server:5984"
      COUCHDB_URL: "http://couchdb-server:5984"
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
      AMQP_SERVER: "amqp://admin:admin@rabbitmq-server/"
      wait_for_rabbitmq_url: "rabbitmq-server:5672"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - rabbitmq-server-node0
      - couchdb-server
    networks:
      - metricq-network

  metricq-source-dummy:
    build:
      context: https://github.com/metricq/metricq-cpp.git
    image: metricq-cxx
    depends_on:
      - rabbitmq-server-node0
      - couchdb-setup
    networks:
      - metricq-network
    restart: unless-stopped
    command: "metricq-source-dummy -s amqp://admin:admin@rabbitmq-server"

  rabbitmq-server-node0:
    build:
      context: ./docker/metricq-clustered/
    image: rabbitmq-cluster-node
    environment:
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node0"
    networks:
      metricq-network:
        aliases:
          - rabbitmq-server
          - rabbitmq-node0
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  rabbitmq-server-node1:
    build:
      context: ./docker/metricq-clustered/
    image: rabbitmq-cluster-node
    environment:
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node1"
    depends_on:
      - rabbitmq-server-node0
    networks:
      metricq-network:
        aliases:
          - rabbitmq-server
          - rabbitmq-node1
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15673:15672"

  rabbitmq-server-node2:
    build:
      context: ./docker/metricq-clustered/
    image: rabbitmq-cluster-node
    environment:
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node2"
    depends_on:
      - rabbitmq-server-node0
    networks:
      metricq-network:
        aliases:
          - rabbitmq-server
          - rabbitmq-node2
    ports:
      - "127.0.0.1:5674:5672"
      - "127.0.0.1:15674:15672"

  couchdb-server:
    image: couchdb:3
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
    networks:
      - metricq-network
    ports:
      - "127.0.0.1:5984:5984"
    command: /opt/couchdb/bin/couchdb

  couchdb-setup:
    build:
      context: ./docker/couchdb-setup/
    image: metricq-couchdb-setup
    depends_on:
      - couchdb-server
    networks:
      - metricq-network

  grafana-server:
    build:
      context: https://github.com/metricq/grafana-metricq-datasource.git
    image: metricq-grafana-server
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - metricq-grafana
    networks:
      - metricq-network

  metricq-grafana:
    build:
      context: https://github.com/metricq/metricq-grafana.git
      args:
        - SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0-dev
    image: metricq-grafana
    environment:
      wait_for_rabbitmq_url: "rabbitmq-server:5672"
      WAITFORIT_TIMEOUT: 0
      metricq_url: "amqp://admin:admin@rabbitmq-server/"
    depends_on:
      - rabbitmq-server-node0
    ports:
      - "127.0.0.1:4000:4000"
    restart: unless-stopped
    networks:
      - metricq-network

  metricq-webview:
    build:
      context: https://github.com/metricq/metricq-webview.git
      args:
        - METRICQ_BACKEND=http://localhost:4000
        - METRICQ_BACKEND_AUTH=
    depends_on:
      - metricq-grafana
    ports:
      - "127.0.0.1:3002:80"
    restart: unless-stopped
    networks:
      - metricq-network
      
networks:
  metricq-network:
    driver: bridge
