FROM python:3-slim
LABEL maintainer="mario.bielert@tu-dresden.de"

RUN useradd -m metricq
RUN pip install virtualenv
RUN apt-get update && apt-get install -y protobuf-compiler

USER metricq
COPY --chown=metricq:metricq . /home/metricq/metricq

WORKDIR /home/metricq
RUN virtualenv venv

WORKDIR /home/metricq/metricq
RUN . /home/metricq/venv/bin/activate && pip install .
