apiVersion: 1

groups:
  - orgId: 1
    name: combinators-1m
    folder: MetricQ Development
    interval: 1m
    rules:
      - uid: ffvvvhmywdts0d
        title: Missing Data for Input Metrik
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: |-
                (
                  (metricq_gombinator_worker_max_input_queue > 3000)
                  *
                  on (metric, token) group_right(input)
                  (metricq_gombinator_worker_input_waiting == 1)
                )
                or on() vector(0)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: metricq-gombinator
        panelId: 8
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          __dashboardUid__: metricq-gombinator
          __panelId__: "8"
        labels: {}
        isPaused: false
        notification_settings:
          receiver: empty
