name: C++ Interface

on: [push]


jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [g++-7, g++-8, g++-9, clang++-6.0, clang++-8, clang++-9]

    steps:
    - uses: actions/checkout@v2
    - name: Install Protobuf
      run: |
        sudo apt update
        sudo apt install libprotoc-dev protobuf-compiler
    - name: Run CMake configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake .
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .

  build-macos:

    runs-on: macos

    strategy:
      matrix:
        compiler: [g++-8, g++-9, c++]

    steps:
    - uses: actions/checkout@v2
    - name: Install Protobuf
      run: |
        brew install protobuf openssl@1.1
    - name: Run CMake configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .
