name: Build C++ Interface

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Protobuf
      run: |
        - sudo apt update
        - sudo apt install libprotoc-dev protobuf-compiler
    - name: Run CMake configure
      run: cmake .
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .
