name: Integration tests

on: 
  push: {}
  repository_dispatch:
    types: [integration-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate docker compose config
        uses: cuchi/jinja2-action@v1.1.0
        with:
          template: tests/docker-compose-test.yml.j2
          output_file: tests/docker-compose-test.yml
          strict: true
          variables: |
            manager=${{ github.event.client_payload.manager_ref }}
            cxx=${{ github.event.client_payload.cxx_ref }}
      - name: Build the stack
        run: docker-compose -f tests/docker-compose-test.yml up -d
      - name: Sleep a bit (why not?)
        run: sleep 30
      - name: "Test 1: Setup config"
        run: "docker run --rm --network tests_metricq-network curlimages/curl:latest curl --retry-connrefused --retry 5 --retry-delay 10 -X PUT -H \"Content-Type: application/json\" http://admin:admin@couchdb-server:5984/config/source-dummy-test1 -d '{}'"
      - name: "Test 1: simple source test"
        run: docker-compose -f tests/docker-compose-test.yml run --rm metricq-cxx metricq-source-dummy -s amqp://admin:admin@rabbitmq-server/ --token source-dummy-test1 --metric "dummy.pets" --messages-per-chunk 10 --chunk-count 100
